name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Cache files
        uses: actions/cache/save@v4
        with:
          path: .
          key: project

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: .
          key: project
      - name: Build
        run: npm run build

  format:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: .
          key: project
      - name: Run prettier
        run: npm run format:check

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: .
          key: project
      - name: Run ESLint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: .
          key: project
      - name: Run unit tests
        run: npm run test

  e2e:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: .
          key: project
      - name: Install dependencies
        run: npx playwright install --with-deps
      - name: Run dev server
        run: nohup npm run start > serve.log 2>&1 &
      - name: Run e2e tests
        run: npx --yes wait-on http://localhost:4200/ && npm run e2e
